networks:  # Networks must be defined FIRST
  app-network:
    driver: bridge

services:
  display_ui:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: display_ui
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./application.py:/app/application.py
    environment:
      DB_HOST: "host.docker.internal"
      DB_PORT: "5432"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "AnujS@003"
      PYTHONUNBUFFERED: "1"
      MODEL_SERVER_URL: "http://host.docker.internal:5002"
    ports:
      - "8000:8000"
    networks:
      - app-network  # Now properly references the defined network
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000/ || exit 1"]
