services:
  postgres:
    image: postgres:15
    container_name: rss_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: rss_user
      POSTGRES_PASSWORD: rss_password
      POSTGRES_DB: rss_feed
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initialisation:/docker-entrypoint-initdb.d
  data_extract:
    build: 
      context: .
      dockerfile: Dockerfile.db
    container_name: data_extract
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_HOST: "postgres"
      DB_NAME: "rss_feed"
      DB_USER: "rss_user"
      DB_PASSWORD: "rss_password"
  
  display_ui:
    build: 
      context: .
      dockerfile: Dockerfile.app
    container_name: display_ui
    restart: unless-stopped
    depends_on:
      - data_extract
    environment:
      DB_HOST: "postgres"
      DB_NAME: "rss_feed"
      DB_USER: "rss_user"
      DB_PASSWORD: "rss_password"