stages:
  extract_data:
    cmd: python model/extract_news_data.py
    params:
      - extract_data.configuration
      - extract_data.feeds
      - extract_data.category_patterns

  extract_best_model:
    cmd: python model/register_best_model.py
    params:
      - model.num_neurons
      - model.lr
      - model.batch_size
      - model.epochs
      - model.runs
    deps:
      - data/BBC News Train.csv

  fine_tune_best_model:
    cmd: python model/fine_tune_best_model.py
    deps:
      - mlartifacts
      - data/news_feed.csv
    metrics:
      - metrics/classification_report.json
      - metrics/training_history.json