model:
  num_neurons: [64, 128, 256]
  lr: [1e-4, 1e-3, 1e-2]
  batch_size: [32, 64]
  epochs: [3]
  runs: 8

extract_data:
  configuration:
    database: postgres
    user: postgres
    host: localhost
    password: AnujS@003
    port: 5432
  feeds:
    Times Of India: https://timesofindia.indiatimes.com/rssfeeds/1221656.cms
    TOI: https://timesofindia.indiatimes.com/rssfeedstopstories.cms
    The Hindu: https://www.thehindu.com/news/national/?service=rss
    Economic Times: https://economictimes.indiatimes.com/rssfeedstopstories.cms
    India Today: https://www.indiatoday.in/rss/home
    NDTV: https://feeds.feedburner.com/ndtvnews-top-stories
  category_patterns:
    sport: \b(?:sport|sports|cricket|football)\b
    tech: \b(?:tech|technology|AI|artificial intelligence)\b
    entertainment: \b(?:entertainment|movie|bollywood|hollywood|actor|actress)\b
    business: \b(?:business|economy|market|stock|finance)\b
    politics: \b(?:politics|election|minister|government|parliament)\b

data:
  date: '2025-04-29'
